default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

development:
  <<: *default
  database: carwash_development

test:
  <<: *default
  database: carwash_test

production:
  <<: *default
  database: carwash_production
